# This is a basic workflow to help you get started with Actions

name: apy_robot

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
            node-version: 14.x
      - name: npm install
        run: |
            npm install
      - name: "run apy_robot"
        run: |
            node apys.js    
      - run : git config --global --add safe.directory /github/workspace      
      - name: Git Commit/Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "update data"
